version: '3.7'

services:
  find-a-mentor-api:
    restart: always
    image: node:10-alpine
    container_name: find-a-mentor-api
    command: sh -c "yarn install; yarn start:prod"
    volumes:
      - ./:/usr/src
    ports:
      - 3000:3000
    working_dir: /usr/src
    environment:
      - MONGO_DATABASE_URL=mongodb://find-a-mentor-mongo/codingcoach

  find-a-mentor-mongo:
    restart: always
    image: mongo:4
    container_name: find-a-mentor-mongo
    hostname: find-a-mentor-mongo
    volumes:
      - './local-mongo:/data/db'
    ports:
      - 27017:27017
